// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgyavqxoxzaeukhjbtcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRneWF2cXhveHphZXVraGpidGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDc1NDUsImV4cCI6MjA2MDgyMzU0NX0.fqCDkJS0Gp0gWp2FBADZ8q4MCm7qLYcUXn2K4i2LSu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);